const env = {
    VITE_HRIS_BACKEND_URL_DEV: import.meta.env.VITE_HRIS_BACKEND_URL_DEV,
    VITE_HRIS_BACKEND_URL_PROD: import.meta.env.VITE_HRIS_BACKEND_URL_PROD,
    VITE_PAYROLL_BACKEND_URL_DEV: import.meta.env.VITE_PAYROLL_BACKEND_URL_DEV,
    VITE_PAYROLL_BACKEND_URL_PROD: import.meta.env.VITE_PAYROLL_BACKEND_URL_PROD,
}

export default env;